name: CI

on:
  push:
    branches-ignore: [ "main" ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches-ignore: [ "main" ]
    paths-ignore:
      - '**.md'

  # Adds ability to run this workflow manually
  workflow_dispatch:


jobs:

  lint:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter black
        uses: psf/black@stable
        with:
          options: "--check"

  tests:
    name: Run unit-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run tests
        run: pytest
